package com.yx.admirer.dataobject;

import java.util.Date;

public class CelebritiesDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column celebrities.id
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column celebrities.name
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column celebrities.info
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column celebrities.dynasty
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    private String dynasty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column celebrities.create_time
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column celebrities.id
     *
     * @return the value of celebrities.id
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column celebrities.id
     *
     * @param id the value for celebrities.id
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column celebrities.name
     *
     * @return the value of celebrities.name
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column celebrities.name
     *
     * @param name the value for celebrities.name
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column celebrities.info
     *
     * @return the value of celebrities.info
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column celebrities.info
     *
     * @param info the value for celebrities.info
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column celebrities.dynasty
     *
     * @return the value of celebrities.dynasty
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    public String getDynasty() {
        return dynasty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column celebrities.dynasty
     *
     * @param dynasty the value for celebrities.dynasty
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    public void setDynasty(String dynasty) {
        this.dynasty = dynasty == null ? null : dynasty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column celebrities.create_time
     *
     * @return the value of celebrities.create_time
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column celebrities.create_time
     *
     * @param createTime the value for celebrities.create_time
     *
     * @mbg.generated Tue Dec 03 10:33:08 GMT+08:00 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}