package com.yx.admirer.dao;

import com.yx.admirer.dataobject.CelebritiesDO;

public interface CelebritiesDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table celebrities
     *
     * @mbg.generated Tue Dec 03 10:33:09 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table celebrities
     *
     * @mbg.generated Tue Dec 03 10:33:09 GMT+08:00 2019
     */
    int insert(CelebritiesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table celebrities
     *
     * @mbg.generated Tue Dec 03 10:33:09 GMT+08:00 2019
     */
    int insertSelective(CelebritiesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table celebrities
     *
     * @mbg.generated Tue Dec 03 10:33:09 GMT+08:00 2019
     */
    CelebritiesDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table celebrities
     *
     * @mbg.generated Tue Dec 03 10:33:09 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(CelebritiesDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table celebrities
     *
     * @mbg.generated Tue Dec 03 10:33:09 GMT+08:00 2019
     */
    int updateByPrimaryKey(CelebritiesDO record);
}